CREATE DATABASE ProductDB;
CREATE DATABASE UsersDB;

USE ProductDB;

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(255),
    price DECIMAL(10, 2)
);

INSERT INTO products (name, description, category, price) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with adjustable DPI.', 'Electronics', 19.99),
('Bluetooth Speaker', 'Portable Bluetooth speaker with great sound quality.', 'Electronics', 29.99),
('Laptop Stand', 'Adjustable stand for laptops with cooling features.', 'Accessories', 25.50),
('Smartphone', 'Latest Android smartphone with high-resolution camera.', 'Electronics', 599.99),
('Gaming Keyboard', 'Mechanical keyboard with customizable RGB lighting.', 'Electronics', 89.99),
('Wireless Earbuds', 'Noise-canceling wireless earbuds with excellent sound clarity.', 'Electronics', 49.99),
('Smartwatch', 'Smartwatch with fitness tracking and heart-rate monitor.', 'Wearables', 99.99),
('USB-C Hub', 'Multi-port USB-C hub for enhanced connectivity.', 'Accessories', 35.00),
('Laptop Charger', 'Fast charging laptop charger for modern laptops.', 'Accessories', 20.00),
('Power Bank', 'Portable power bank with 20,000mAh capacity.', 'Accessories', 40.00),
('Gaming Headset', 'Comfortable gaming headset with surround sound.', 'Electronics', 65.00),
('Bluetooth Mouse', 'Compact Bluetooth mouse with long battery life.', 'Electronics', 24.99),
('HD Webcam', '1080p HD webcam for clear video conferencing.', 'Electronics', 45.99),
('External Hard Drive', '1TB external hard drive for secure data storage.', 'Accessories', 59.99),
('Portable SSD', 'Fast 500GB portable SSD with high transfer speed.', 'Accessories', 109.99),
('Electric Kettle', 'Electric kettle with rapid boiling feature.', 'Home Appliances', 39.99),
('Coffee Maker', 'Compact coffee maker for quick coffee brewing.', 'Home Appliances', 49.99),
('Air Fryer', 'Air fryer for healthy and crispy cooking.', 'Home Appliances', 79.99),
('Microwave Oven', 'Compact microwave oven with defrost function.', 'Home Appliances', 120.00),
('Blender', 'Powerful blender for smoothies and soups.', 'Home Appliances', 35.50),
('Handheld Vacuum', 'Portable handheld vacuum cleaner for quick cleaning.', 'Home Appliances', 45.00),
('Iron', 'Steam iron with anti-drip and anti-calcium features.', 'Home Appliances', 50.00),
('Water Purifier', 'Water purifier with 5-stage filtration system.', 'Home Appliances', 85.00),
('Toaster', 'Two-slice toaster with adjustable browning control.', 'Home Appliances', 29.99),
('Smart Light Bulb', 'Smart LED bulb that can be controlled by phone.', 'Home Electronics', 15.99),
('Smart Thermostat', 'Energy-efficient smart thermostat for home automation.', 'Home Electronics', 120.00),
('Bluetooth Car Kit', 'Wireless Bluetooth kit for hands-free driving.', 'Automotive', 34.99),
('Car Phone Mount', 'Universal car phone mount with adjustable grip.', 'Automotive', 18.00),
('Jump Starter', 'Portable jump starter for emergency situations.', 'Automotive', 55.00),
('Car Vacuum Cleaner', 'Compact vacuum cleaner designed for car interiors.', 'Automotive', 39.99),
('Tire Inflator', 'Portable tire inflator with digital gauge.', 'Automotive', 45.00),
('Electric Scooter', 'Foldable electric scooter with fast-charging battery.', 'Transport', 299.99),
('Bike Lock', 'Heavy-duty bike lock with combination security.', 'Accessories', 19.99),
('Camping Tent', 'Durable camping tent for 4 people with waterproof design.', 'Outdoor', 120.00),
('Sleeping Bag', 'Comfortable sleeping bag for outdoor camping.', 'Outdoor', 35.50),
('Camping Stove', 'Portable camping stove for cooking on the go.', 'Outdoor', 55.00),
('LED Lantern', 'Bright LED lantern for outdoor activities.', 'Outdoor', 25.00),
('Fishing Rod', 'High-quality fishing rod for freshwater fishing.', 'Outdoor', 45.99),
('Backpack', 'Large capacity backpack for travel and hiking.', 'Outdoor', 30.00),
('Yoga Mat', 'Non-slip yoga mat for comfortable workout sessions.', 'Fitness', 19.50),
('Dumbbells', 'Adjustable dumbbells for home workouts.', 'Fitness', 69.99),
('Resistance Bands', 'Set of resistance bands for strength training.', 'Fitness', 18.00),
('Jump Rope', 'Durable jump rope for cardio workouts.', 'Fitness', 15.00),
('Treadmill', 'Electric treadmill with multiple speed settings.', 'Fitness', 350.00),
('Home Gym Set', 'Complete home gym set with weights and accessories.', 'Fitness', 200.00),
('Cycling Gloves', 'Breathable cycling gloves for comfort and protection.', 'Sports', 14.99),
('Football', 'Professional-grade football for outdoor play.', 'Sports', 24.99),
('Soccer Shoes', 'Comfortable soccer shoes with excellent grip.', 'Sports', 50.00),
('Tennis Racket', 'Lightweight tennis racket for recreational use.', 'Sports', 45.00),
('Baseball Glove', 'High-quality leather baseball glove.', 'Sports', 55.00),
('Golf Clubs', 'Complete set of golf clubs for beginners and pros.', 'Sports', 300.00),
('Basketball', 'Durable basketball for indoor and outdoor play.', 'Sports', 30.00),
('Ping Pong Paddle', 'Professional ping pong paddle with high-speed spin.', 'Sports', 20.00),
('Boxing Gloves', 'Boxing gloves with padding for safety and comfort.', 'Sports', 40.00),
('Camping Chair', 'Lightweight folding camping chair for outdoor relaxation.', 'Outdoor', 30.00),
('Solar Charger', 'Portable solar charger for powering devices on the go.', 'Outdoor', 40.00),
('Hiking Boots', 'Sturdy hiking boots with waterproof feature.', 'Outdoor', 70.00),
('Trekking Poles', 'Adjustable trekking poles for easier hiking.', 'Outdoor', 25.00),
('Binoculars', 'High-quality binoculars for birdwatching and outdoor use.', 'Outdoor', 50.00),
('Bicycle Helmet', 'Protective helmet for cycling and outdoor activities.', 'Sports', 35.00),
('Skateboard', 'Durable skateboard with smooth ride.', 'Sports', 55.00),
('Rollerblades', 'Inline skates for recreational and competitive use.', 'Sports', 70.00),
('Portable Grill', 'Compact portable grill for outdoor cooking.', 'Outdoor', 45.00),
('Picnic Basket', 'Wicker picnic basket with dining accessories.', 'Outdoor', 30.00),
('Hydration Pack', 'Hydration pack for biking, hiking, and outdoor activities.', 'Outdoor', 25.00),
('Fitness Tracker', 'Wearable fitness tracker with heart-rate monitor.', 'Wearables', 49.99),
('Smart Glasses', 'Wearable smart glasses for augmented reality experiences.', 'Wearables', 150.00),
('Electric Toothbrush', 'Rechargeable electric toothbrush with multiple modes.', 'Health & Beauty', 45.00),
('Shaving Kit', 'Complete shaving kit with razor, brush, and accessories.', 'Health & Beauty', 30.00),
('Hair Dryer', 'High-power hair dryer with multiple settings.', 'Health & Beauty', 60.00),
('Face Mask', 'High-quality reusable face mask for protection and comfort.', 'Health & Beauty', 10.00),
('Sunscreen', 'Broad-spectrum sunscreen for skin protection.', 'Health & Beauty', 18.00),
('Lip Balm', 'Hydrating lip balm with SPF protection.', 'Health & Beauty', 5.00),
('Nail Clipper Set', 'Professional nail clipper set with stainless steel blades.', 'Health & Beauty', 12.99),
('Beard Grooming Kit', 'Complete grooming kit for beards with comb and oil.', 'Health & Beauty', 20.00),
('Makeup Brush Set', 'High-quality makeup brushes for flawless application.', 'Health & Beauty', 25.00),
('Face Cream', 'Moisturizing face cream for daily skincare routine.', 'Health & Beauty', 22.00),
('Electric Razor', 'Cordless electric razor for a close and comfortable shave.', 'Health & Beauty', 50.00),
('Hair Straightener', 'Hair straightener with adjustable heat settings.', 'Health & Beauty', 40.00),
('Electric Massager', 'Portable electric massager for relaxation and stress relief.', 'Health & Beauty', 60.00),
('Body Lotion', 'Rich body lotion for hydration and smooth skin.', 'Health & Beauty', 18.00),
('Cotton Towels', 'Soft cotton towels for daily use.', 'Home Goods', 15.00),
('Blanket', 'Cozy and soft blanket for cold nights.', 'Home Goods', 35.00),
('Curtains', 'Stylish curtains for home decoration and privacy.', 'Home Goods', 50.00),
('Table Lamp', 'Adjustable table lamp for reading or work.', 'Home Goods', 20.00),
('Wall Clock', 'Modern wall clock with elegant design.', 'Home Goods', 25.00),
('Rug', 'Comfortable rug for home interiors.', 'Home Goods', 40.00),
('Bedding Set', 'Complete bedding set including sheets and pillowcases.', 'Home Goods', 55.00),
('Candles', 'Scented candles for relaxation and ambiance.', 'Home Goods', 15.00),
('Curtain Rod', 'Durable curtain rod for easy installation.', 'Home Goods', 20.00),
('Shelf', 'Wooden shelf for home storage and display.', 'Home Goods', 30.00),
('Vase', 'Decorative vase for fresh or artificial flowers.', 'Home Goods', 25.00);

SELECT * FROM products LIMIT 10;

USE UsersDB;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);